# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.23
# 
# >> macros
# << macros

Name:       rssreaderconfig
Summary:    SOCAM feeds page configuration
Version:    1.0.0
Release:    1
Group:      Applications/Internet
License:    GPLv2
Source0:    %{name}-%{version}.tar.gz
BuildRequires:  pkgconfig(QtCore) >= 4.7.0
BuildRequires:  pkgconfig(QtGui)


%description
SOCAM feeds page configuration. Allows to select a template from a catalog and set the feed URLs.



%prep
%setup -q -n %{name}-%{version}


%build
# >> build pre
# << build pre

qmake rssreaderconfig.pro
make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake_install

#mkdir -p %{buildroot}%{_datadir}/socam/feeds/
#cp %{_builddir}/%{name}-%{version}/templates %{buildroot}%{_datadir}/socam/feeds/ -r




%files
%defattr(-,root,root,-)

%{_libdir}/qt4/imports/es/zed/socam/rssreader
%{_libdir}/duicontrolpanel

#%{_libdir}/qt4/imports/eszed/socam/rssreader/librssreader.so
#%{_libdir}/qt4/imports/es/zed/socam/rssreader/qmldir
#%{_libdir}/qt4/imports/es/zed/socam/rssreader/TemplateCell.qml
#%{_libdir}/qt4/imports/es/zed/socam/rssreader/TemplateCellContent.qml
#%{_libdir}/qt4/imports/es/zed/socam/rssreader/TemplateCellPreview.qml
#%{_libdir}/qt4/imports/es/zed/socam/rssreader/TemplateRenderer.qml
#%{_libdir}/qt4/imports/es/zed/socam/rssreader/storage.js

%{_bindir}/rssreaderconfig

%{_datadir}/socam/feeds/templates/portrait/*
%{_datadir}/socam/feeds/templates/landscape/*




# >> files
# << files

